# Merge tl_types.luau.inc and schema_types.luau.inc into tl_types.luau
# Usage: cmake -D TL_INC=<path> -D SCHEMA_INC=<path> -D OUT=<path> -P MergeLuauHintIncs.cmake
if(NOT TL_INC OR NOT SCHEMA_INC OR NOT OUT)
  message(FATAL_ERROR "MergeLuauHintIncs.cmake: TL_INC, SCHEMA_INC, OUT required")
endif()

set(TL_CONTENT "")
foreach(tl_inc_file IN LISTS TL_INC)
  file(READ "${tl_inc_file}" TL_INC_CONTENT)
  string(APPEND TL_CONTENT "${TL_INC_CONTENT}\n")
endforeach()

file(READ "${SCHEMA_INC}" SCHEMA_CONTENT)
set(DONT_MODIFY_TITLE "----------------- GENERATED BY CMAKE, DON'T MODIFY! -----------------\n")
set(MERGED "${DONT_MODIFY_TITLE}\n${TL_CONTENT}\n\n${SCHEMA_CONTENT}\n")
file(WRITE "${OUT}" "${MERGED}")
message(STATUS "Merged luau hints -> ${OUT}")
