if(NOT INC OR NOT OUT OR NOT RETURN_VALUE)
  message(FATAL_ERROR "wrap_luau_hint_inc.cmake: INC, OUT, RETURN_VALUE required")
endif()

file(READ "${INC}" INC_CONTENT)

set(DONT_MODIFY_TITLE "----------------- GENERATED BY CMAKE, DON'T MODIFY! -----------------\n")
set(WRAPPED "${DONT_MODIFY_TITLE}\n${INC_CONTENT}\n\nreturn ${RETURN_VALUE}\n")
get_filename_component(OUT_DIR "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUT_DIR}")
file(WRITE "${OUT}" "${WRAPPED}")
message(STATUS "Generated luau hints -> ${OUT}")
