#pragma once

#ifdef TL_ENABLE_PROFILE
#include "optick.h"

#define PROFILE_MAIN_FRAME() OPTICK_FRAME("MainThread")
#define PROFILE_THREAD(name) OPTICK_THREAD(name)
#define PROFILE_SECTION() OPTICK_EVENT()
#define PROFILE_TAG(name, var) OPTICK_TAG(name, var)

#define PROFILE_AI_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::AI)
#define PROFILE_ANIMATION_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Animation)
#define PROFILE_AUDIO_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Audio)
#define PROFILE_DEBUG_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Debug)
#define PROFILE_CAMERA_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Camera)
#define PROFILE_CLOTH_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Cloth)
#define PROFILE_GAMELOGIC_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GameLogic)
#define PROFILE_INPUT_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Input)
#define PROFILE_NAVIGATION_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Navigation)
#define PROFILE_NETWORK_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Network)
#define PROFILE_PHYSICS_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Physics)
#define PROFILE_RENDERING_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Rendering)
#define PROFILE_SCENE_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Scene)
#define PROFILE_SCRIPT_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Script)
#define PROFILE_STREAMING_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Streaming)
#define PROFILE_UI_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::UI)
#define PROFILE_VFX_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::VFX)
#define PROFILE_VISIBILITY_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Visibility)
#define PROFILE_WAIT_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::Wait)
#define PROFILE_WAITEMPTY_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::WaitEmpty)
#define PROFILE_IO_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::IO)
#define PROFILE_GPU_CLOTH_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_Cloth)
#define PROFILE_GPU_LIGHTING_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_Lighting)
#define PROFILE_GPU_POSTFX_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_PostFX)
#define PROFILE_GPU_REFLECTIONS_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_Reflections)
#define PROFILE_GPU_SCENE_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_Scene)
#define PROFILE_GPU_SHADOWS_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_Shadows)
#define PROFILE_GPU_UI_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_UI)
#define PROFILE_GPU_VFX_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_VFX)
#define PROFILE_GPU_WATER_SECTION(name) OPTICK_CATEGORY(name, Optick::Category::GPU_Water)

#define PROFILE_SHUTDOWN() OPTICK_SHUTDOWN()
#else
#define PROFILE_MAIN_FRAME()
#define PROFILE_THREAD(name)
#define PROFILE_SECTION()
#define PROFILE_TAG(name, var)
#define PROFILE_AI_SECTION(name)
#define PROFILE_ANIMATION_SECTION(name)
#define PROFILE_AUDIO_SECTION(name)
#define PROFILE_DEBUG_SECTION(name)
#define PROFILE_CAMERA_SECTION(name)
#define PROFILE_CLOTH_SECTION(name)
#define PROFILE_GAMELOGIC_SECTION(name)
#define PROFILE_INPUT_SECTION(name)
#define PROFILE_NAVIGATION_SECTION(name)
#define PROFILE_NETWORK_SECTION(name)
#define PROFILE_PHYSICS_SECTION(name)
#define PROFILE_RENDERING_SECTION(name)
#define PROFILE_SCENE_SECTION(name)
#define PROFILE_SCRIPT_SECTION(name)
#define PROFILE_STREAMING_SECTION(name)
#define PROFILE_UI_SECTION(name)
#define PROFILE_VFX_SECTION(name)
#define PROFILE_VISIBILITY_SECTION(name)
#define PROFILE_WAIT_SECTION(name)
#define PROFILE_WAITEMPTY_SECTION(name)
#define PROFILE_IO_SECTION(name)
#define PROFILE_GPU_CLOTH_SECTION(name)
#define PROFILE_GPU_LIGHTING_SECTION(name)
#define PROFILE_GPU_POSTFX_SECTION(name)
#define PROFILE_GPU_REFLECTIONS_SECTION(name)
#define PROFILE_GPU_SCENE_SECTION(name)
#define PROFILE_GPU_SHADOWS_SECTION(name)
#define PROFILE_GPU_UI_SECTION(name)
#define PROFILE_GPU_VFX_SECTION(name)
#define PROFILE_GPU_WATER_SECTION(name)
#define PROFILE_SHUTDOWN()
#endif