name: Build

on: [push]

jobs:
  build-cmake:
    strategy:
      fail-fast: false
      matrix:
        include:
            - name: Windows
              os: windows-latest
              android: false
            - name: Ubuntu
              os: ubuntu-22.04
              android: false
            - name: MacOS
              os: macOS-latest
              android: false
            - name: Android
              os: ubuntu-latest
              android: true
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Prepare cmake
      uses: lukka/get-cmake@latest

    - name: Prepare Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt update -y
        sudo apt install build-essential make pkg-config gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev -y

    - name: Prepare MacOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew install ninja

    - name: Config cmake(Ubuntu&MacOS)
      if: ${{ !contains(matrix.os, 'windows') && !matrix.android }}
      working-directory: ./game
      run: |
        ${{ matrix.cmake-path }}cmake --preset=CI-Ubuntu-Debug

    - name: Config cmake(MacOS) Debug
      if: ${{ contains(matrix.os, 'macOS') && !matrix.android }}
      working-directory: ./game
      run: |
        ${{ matrix.cmake-path }}cmake --preset=CI-MacOS-Debug

    - name: Config cmake(Windows) Debug
      if: contains(matrix.os, 'windows')
      working-directory: ./game
      run: |
        ${{ matrix.cmake-path }}cmake --preset=CI-Windows-Debug

    - name: Build Debug under PC
      if: ${{ !matrix.android }}
      working-directory: ./game
      run: ${{ matrix.cmake-path }}cmake --build cmake-build-debug

    - name: Config cmake(Ubuntu) Release
      if: ${{ contains(matrix.os, 'ubuntu') && !matrix.android }}
      working-directory: ./game
      run: |
        ${{ matrix.cmake-path }}cmake --preset=CI-Ubuntu-Release

    - name: Config cmake(MacOS) Release
      if: ${{ contains(matrix.os, 'macOS') && !matrix.android }}
      working-directory: ./game
      run: |
        ${{ matrix.cmake-path }}cmake --preset=CI-MacOS-Release

    - name: Config cmake(Windows) Release
      if: contains(matrix.os, 'windows')
      working-directory: ./game
      run: |
        ${{ matrix.cmake-path}}cmake --preset=CI-Windows-Release

    - name: Build Release under PC
      if: ${{ !matrix.android }}
      working-directory: ./game
      run: ${{ matrix.cmake-path }}cmake --build cmake-build-release

    - name: Precompile schema parser
      if: runner.os == 'Linux' && matrix.android
      working-directory: ./game
      run: |
        ${{ matrix.cmake-path }}cmake --preset=default
        ${{ matrix.cmake-path }}cmake --build cmake-build --target schema_parser
        ${{ matrix.cmake-path }}cmake --build cmake-build --target run_schema_parser

    - name: Prepare Android JDK
      if: matrix.android
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Android SDK
      if: matrix.android
      uses: android-actions/setup-android@v3

    - name: Prepare Android Project
      if: matrix.android
      run: |
        sudo apt update -y
        sudo apt install cmake ninja-build -y
        yes | sdkmanager --licenses
        cp -r ./game ./android/app/jni/
        cp -r game/assets android/app/src/main/assets/
        chmod +x ./android/gradlew

    - name: Build under Android
      if: matrix.android
      working-directory: ./android
      run: |
        ./gradlew build

    - name: Assemble Release APK
      if: matrix.android
      working-directory: ./android
      run: |
        ./gradlew assembleRelease

    - name: Package under PC
      if: ${{ !matrix.android }}
      working-directory: ./game
      run: ${{ matrix.cmake-path }}cmake --build cmake-build-release --target install --config Release

    - name: Upload Ubuntu Build Artifact
      if: ${{ contains(matrix.os, 'ubuntu') && !matrix.android }}
      uses: actions/upload-artifact@v4
      with:
        name: TreasureLooter-${{ matrix.os }}
        path: game/install/ubuntu
        retention-days: 7

    - name: Upload Windows Build Artifact
      if: ${{ contains(matrix.os, 'windows') && !matrix.android }}
      uses: actions/upload-artifact@v4
      with:
        name: TreasureLooter-${{ matrix.os }}
        path: game/install/windows
        retention-days: 7

    - name: Upload MacOS Build Artifact
      if: ${{ contains(matrix.os, 'macOS') && !matrix.android }}
      uses: actions/upload-artifact@v4
      with:
        name: TreasureLooter-${{ matrix.os }}
        path: game/install/macOS
        retention-days: 7

    - name: Upload Android Build Artifact
      if: matrix.android
      uses: actions/upload-artifact@v4
      with:
        name: TreasureLooter-android
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 7