name: Publish Release

on:
  push:
    branches:
      - auto_release
    # tags:
    #   - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          pattern: TreasureLooter-*
          merge-multiple: false
      - name: output files
        run: ls -R
      - name: Deploy
        uses: softprops/action-gh-release@v2
        with:
          files: |
            TreasureLooter-ubuntu
            TreasureLooter-windows
            TreasureLooter-macOS
          prerelease: true